-- Write a query to find the employee id, name (last_name) along with their manager_id and name (last_name).

SELECT TBL1.EMPLOYEE_ID, TBL1.LAST_NAME, TBL1.MANAGER_ID, TBL2.LAST_NAME 
FROM (SELECT A.EMPLOYEE_ID, A.LAST_NAME, A.MANAGER_ID FROM employees AS A ORDER BY A.MANAGER_ID) AS TBL1 
INNER JOIN (SELECT B.EMPLOYEE_ID, B.LAST_NAME FROM employees AS B) AS TBL2 ON TBL1.MANAGER_ID = TBL2.EMPLOYEE_ID
ORDER BY TBL1.MANAGER_ID;